apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: front-container
          image: hapsy/webportal-front:latest
          ports:
            - containerPort: 80
