name: 'front develop test'
on:
  pull_request:
    branches: [ develop ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@master
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci --legacy-peer-deps
    - name: 'Create .env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: linting typescript
      if: always()
      run: npm run lint:ts
    - name: linting styles
      if: always()
      run: npm run lint:styles
    - name: unit testing
      run: npm run test:unit
    - name: run storybook in bg
      if: always()
      run: npm run storybook &
    - name: screenshot regress testing
      run: npm run test:ui
    - name: npm run production build
      if: always()
      run: npm run build:prod
