name: 'deploy front release'

on:
  push:
    branches:
      - 'release/**'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: 'Create .env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: npm run production build
      if: always()
      run: npm run build:prod
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: hapsy/webportal-front
        tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          hapsy/webportal-front:latest
          hapsy/webportal-front:${{  github.ref_name }}
        labels: ${{ steps.meta.outputs.labels }},
    - name: Update yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'argocd/prod/deployment.yaml'
        propertyPath: 'spec.template.spec.containers.0.image'
        value: hapsy/webportal-front:${{  github.ref_name }}
        commitChange: false
    - name: Commit the changes for argocd
      run: | 
        git config --global user.name 'hardpsycho'
        git config --global user.email 'harddeveloper@outlook.com'
        git fetch
        git checkout develop
        git add .
        git commit -m "auto: update image version in manifest"
        git push origin develop
